### ISSUE TITLE
Notebook  rssynergia-linear-8-2-IOTA-SC.ipynb  fails on Jupyter server

### ISSUE THREAD

**Issue by bruhwile** [radiasoft/rssynergia#2]
I did a git clone of the rssynergia repo in the Jupyter terminal during a demo.
In cell #6, there's an error because the lattice file isn't found.
The notebook should run without errors in this context.

Screenshot of the error:
![image](https://cloud.githubusercontent.com/assets/3825435/17817707/02c9c780-65fd-11e6-833d-d6e4cf175bb4.png)

**Comment by cchall** [comment]
Was the ioptics repo cloned to the same directory?

**Comment by bruhwile** [comment]
No, the ioptics repo wasn't there.
The notebook needs one more instance of ../ in the path, even if the
ioptics notebook is present.

In any case, we don't want rswarp/ or rssynergia/ to depend on each other
or on ioptics/
It's OK for ioptics/ to depend on both rswarp/ and rssynergia/

So that notebook should be moved from rssynergia/ to ioptics/

Thanks,
David


On Fri, Aug 19, 2016 at 11:16 AM, cchall <notifications@github.com> wrote:

Was the ioptics repo cloned to the same directory?
>
>
>
