### ISSUE TITLE
how to 'Create a Synergia development environment on your laptop or desktop'?

### ISSUE THREAD

**Issue by Landau1908** [radiasoft/rssynergia#8]
Following the instructions described below, I get an error which displayed at the end.
"
Install VirtualBox on your computer
https://www.virtualbox.org/wiki/Downloads

Install Vagrant on your computer
https://www.vagrantup.com/docs/installation/

Create a directory in a linux, unix or cygwin environment
> mkdir synergia_devel
> cd synergia_devel

In this directory, create a text file named "Vagrantfile" with the following contents:

# -*- mode: ruby -*-
Vagrant.configure(2) do |config|
  config.vm.box = "radiasoft/beamsim"
  config.vm.hostname = "rs"
  config.ssh.insert_key = false
  config.ssh.forward_x11 = true
  config.vm.network "forwarded_port", guest:8000, host:8000
  config.vm.synced_folder ".", "/vagrant", disabled: false
end

Invoke 'vagrant' as follows
> vagrant up

Wait several minutes, because the container is large
"

C:\synergia_devel>vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'radiasoft/beamsim' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
The box 'radiasoft/beamsim' could not be found or
could not be accessed in the remote catalog. If this is a private
box on HashiCorp's Vagrant Cloud, please verify you're logged in via
`vagrant login`. Also, please double-check the name. The expanded
URL and error message are shown below:

URL: ["https://vagrantcloud.com/radiasoft/beamsim"]
Error: The requested URL returned error: 404 Not Found

By the way: my system is Win10

**Comment by robnagler** [comment]
@Landau1908 these instructions are old so please ignore them. We no longer build VirtualBox image for beamsim.  Instead, follow these instructions:

```sh
https://github.com/radiasoft/sirepo/wiki/Development#pc-install
```
